export const timeLineDataDay1 = [
  {
    date: "8:00 AM",
    h3: "Solo Dance",
    h4: "Solo",
    p: "Cultural Event"
  },
  {
    date: "9:00 AM",
    h3: "Duet Dance",
    h4: "Team of 2",
    p: "Cultural Event",
  },
  {
    date: "9:00 AM",
    h3: "Bug Hunter",
    h4: "Solo",
    p: "Technical Event",
  },
  {
    date: "10:00 AM",
    h3: "Mehendi",
    h4: "Solo",
    p: "Cultural Event",
  },
  {
    date: "10:00 AM",
    h3: "Tech Debate",
    h4: "Team of 2",
    p: "Technical Event",
  },
  {
    date: "11:00 AM",
    h3: "Solo Singing",
    h4: "Solo",
    p: "Cultural Event",
  },
  {
    date: "11:00 AM",
    h3: "QuizX",
    h4: "Team of 2",
    p: "Technical Event",
  },
  {
    date: "12:00 PM",
    h3: "Duet Singing",
    h4: "Team of 2",
    p: "Cultural Event",
  },
  {
    date: "12:00 PM",
    h3: "Hackathon",
    h4: "Team of 5",
    p: "Technical Event",
  },
  {
    date: "01:00 PM",
    h3: "Words Worth",
    h4: "Team of 2",
    p: "Cultural Event",
  },
  {
    date: "01:00 PM",
    h3: "Ideathon",
    h4: "Team of 3",
    p: "Technical Event",
  },
  {
    date: "02:00 PM",
    h3: "Mono Acting",
    h4: "Solo",
    p: "Cultural Event",
  },
  {
    date: "03:00 PM",
    h3: "Short Film",
    h4: "Team event(max 20)",
    p: "Cultural Event",
  },
  {
    date: "04:00 PM",
    h3: "Treasure Hunt",
    h4: "Team of 4",
    p: "Cultural Event",
  },
  {
    date: "05:00 PM",
    h3: "Fashion Event",
    h4: "Solo",
    p: "Cultural Event",
  },
  {
    date: "06:00 PM",
    h3: "Yoga",
    h4: "Solo",
    p: "Cultural Seminar",
  },
  {
    date: "07:00 PM",
    h3: "Zumba",
    h4: "Solo",
    p: "Cultural Seminar",
  },
  {
    date: "07:00 PM",
    h3: "Web Technologies",
    h4: "Solo",
    p: "Technical Seminar",
  },
  {
    date: "07:00 PM",
    h3: "CLOUD COMPUTING MEETS BIG DATA",
    h4: "Solo",
    p: "Technical Seminar",
  },
  {
    date: "07:00 PM",
    h3: "ELECTRIC VEHICLES",
    h4: "Solo",
    p: "Technical Seminar",
  },
  {
    date: "07:00 PM",
    h3: "SECRETS OF BRANDING",
    h4: "Solo",
    p: "Technical Seminar",
  },
];

export const timeLineDataDay2 = [
  {
    date: "8:00 AM",
    h3: "Descriptive Sketching",
    h4: "Solo",
    p: "Cultural Event"
  },
  {
    date: "9:00 AM",
    h3: "Slam Poetry",
    h4: "Solo",
    p: "Cultural Event",
  },
  {
    date: "9:00 AM",
    h3: "Code O Quick",
    h4: "Solo",
    p: "Technical Event",
  },
  {
    date: "10:00 AM",
    h3: "Funny Reels",
    h4: "Solo",
    p: "Cultural Event",
  },
  {
    date: "10:00 AM",
    h3: "Poster Presentation",
    h4: "Team of 2",
    p: "Technical Event",
  },
  {
    date: "11:00 AM",
    h3: "Cook of Challenge (MasterChef)",
    h4: "Solo",
    p: "Cultural Event",
  },
  {
    date: "11:00 AM",
    h3: "Technical Treasure Hunt",
    h4: "Team of 2",
    p: "Technical Event",
  },
  {
    date: "12:00 PM",
    h3: "Mask Painting",
    h4: "Solo",
    p: "Cultural Event",
  },
  {
    date: "12:00 PM",
    h3: "Technical Paper Presentation",
    h4: "Team of 2",
    p: "Technical Event",
  },
  {
    date: "01:00 PM",
    h3: "Dumb Charades",
    h4: "Team of 3",
    p: "Cultural Event",
  },
  {
    date: "01:00 PM",
    h3: "CAD Master",
    h4: "Solo",
    p: "Technical Event",
  },
  {
    date: "02:00 PM",
    h3: "Hackathon",
    h4: "Team of 5",
    p: "Technical Event",
  },
  {
    date: "03:00 PM",
    h3: "Dance Workshop",
    h4: "Solo",
    p: "Cultural Seminar",
  },
  {
    date: "04:00 PM",
    h3: "Self Defence",
    h4: "Solo",
    p: "Cultural Seminar",
  },
  {
    date: "05:00 PM",
    h3: "Zumba",
    h4: "Solo",
    p: "Cultural Seminar",
  },
  {
    date: "06:00 PM",
    h3: "Emotional Intelligence",
    h4: "Solo",
    p: "Cultural Seminar",
  },
  {
    date: "07:00 PM",
    h3: "Financial Literacy",
    h4: "Solo",
    p: "Technical Seminar",
  },
  {
    date: "07:00 PM",
    h3: "Higher Studies",
    h4: "Solo",
    p: "Technical Seminar",
  },
  {
    date: "07:00 PM",
    h3: "Cyber Security",
    h4: "Solo",
    p: "Technical Seminar",
  },
  {
    date: "07:00 PM",
    h3: "Google's Driverless Cars and Sophia",
    h4: "Solo",
    p: "Technical Seminar",
  },
];

export const timeLineDataDay3 = [
  {
    date: "9:00 AM",
    h3: "Solo Dance",
    h4: "Solo",
    p: "Cultural Event",
  },
  {
    date: "10:00 AM",
    h3: "Duet Dancing",
    h4: "Team of 2",
    p: "Cultural Event",
  },
  {
    date: "10:00 AM",
    h3: "Website Design",
    h4: "Solo",
    p: "Technical Event",
  },
  {
    date: "11:00 AM",
    h3: "Solo Singing",
    h4: "Solo",
    p: "Cultural Event",
  },
  {
    date: "11:00 AM",
    h3: "Mock Recruitment",
    h4: "Solo",
    p: "Technical Event",
  },
  {
    date: "12:00 PM",
    h3: "Duet Singing",
    h4: "Team of 2",
    p: "Cultural Event",
  },
  {
    date: "12:00 PM",
    h3: "Marketing And Sales",
    h4: "Team of 2",
    p: "Technical Event",
  },
  {
    date: "01:00 PM",
    h3: "FCRIT Jeopardy",
    h4: "Team of 3",
    p: "Cultural Event",
  },
  {
    date: "01:00 PM",
    h3: "Ideathon",
    h4: "Team of 3",
    p: "Technical Event",
  },
  {
    date: "02:00 PM",
    h3: "Photography",
    h4: "Solo",
    p: "Cultural Event",
  },
  {
    date: "02:00 PM",
    h3: "Natural Language Processing",
    h4: "Solo",
    p: "Technical Seminar",
  },
  {
    date: "03:00 PM",
    h3: "Jingle Bells",
    h4: "Solo",
    p: "Cultural Event",
  },
  {
    date: "03:00 PM",
    h3: "Robotics Process Automation",
    h4: "Solo",
    p: "Technical Seminar",
  },
  {
    date: "04:00 PM",
    h3: "Mr and Mrs Etamax",
    h4: "Solo",
    p: "Cultural Event",
  },
  {
    date: "04:00 PM",
    h3: "Ethical Hacking",
    h4: "Solo",
    p: "Technical Seminar",
  },
  {
    date: "05:00 PM",
    h3: "Judge By The Cover",
    h4: "Solo",
    p: "Cultural Event",
  },
  {
    date: "05:00 PM",
    h3: "Blockchain Based Security For IoT",
    h4: "Solo",
    p: "Technical Seminar",
  },
  {
    date: "06:00 PM",
    h3: "Dance Workshop",
    h4: "Solo",
    p: "Cultural Seminar",
  },
  {
    date: "07:00 PM",
    h3: "Self Defence",
    h4: "Solo",
    p: "Cultural Seminar",
  },
  {
    date: "08:00 PM",
    h3: "Yoga",
    h4: "Solo",
    p: "Cultural Seminar",
  },
];
