export const timeLineDataDay1 = [
  {
    date: "9:00 AM",
    h3: "Breaking Records",
    h4: "Solo",
    p: "Cultural Event",
  },
  {
    date: "09:00 AM",
    h3: "Chess",
    h4: "Solo",
    p: "Sports",
  },
  {
    date: "09:00 AM",
    h3: "SkillShot",
    h4: "Solo",
    p: "Fun Event",
  },
  {
    date: "09:00 AM",
    h3: "Yoga",
    h4: "Solo",
    p: "Cultural Event",
  },
  {
    date: "10:00 AM",
    h3: "Snippets",
    h4: "Team of 5-15",
    p: "Cultural Event",
  },
  {
    date: "10:00 AM",
    h3: "Hack It Out",
    h4: "Team of 1-5",
    p: "Technical Event",
  },
  {
    date: "10:00 AM",
    h3: "Cloud Computing Meets Big Data",
    h4: "Solo",
    p: "Technical Seminar",
  },
  {
    date: "10:00 AM",
    h3: "NLP: Build a Chatbot Using Rasa",
    h4: "Solo",
    p: "Technical Seminar",
  },
  {
    date: "10:30 AM",
    h3: "Zumba",
    h4: "Solo",
    p: "Cultural Event",
  },
  {
    date: "11:00 AM",
    h3: "Secrets of Branding",
    h4: "Solo",
    p: "Technical Seminar",
  },
  {
    date: "11:00 AM",
    h3: "CS-GO",
    h4: "Team of 5",
    p: "Gaming",
  },
  {
    date: "12:00 PM",
    h3: "Can You Duet",
    h4: "Team of 2",
    p: "Cultural Event",
  },
  {
    date: "01:00 PM",
    h3: "Mehendi Lagake Rakhna",
    h4: "Solo",
    p: "Cultural Event",
  },
  {
    date: "1:30 PM",
    h3: "Say With Me",
    h4: "Team of 2",
    p: "Cultural Event",
  },
  {
    date: "1:30 PM",
    h3: "MoonWalkers",
    h4: "Solo",
    p: "Cultural Event"
  },
  {
    date: "2:30 PM",
    h3: "The ShowStopper",
    h4: "Solo",
    p: "Cultural Event",
  },
  {
    date: "02:30 PM",
    h3: "Avidhrita",
    h4: "Team of 3",
    p: "Technical Event",
  },
  {
    date: "03:00 PM",
    h3: "Valorant",
    h4: "Team of 5",
    p: "Gaming",
  },
  {
    date: "3:00 PM",
    h3: "Hop Till You Drop",
    h4: "Team of 2",
    p: "Cultural Event",
  },
  {
    date: "04:00 PM",
    h3: "Technical Debate",
    h4: "Team of 1-2",
    p: "Technical Event",
  },
  {
    date: "4:00 PM",
    h3: "Ankahi",
    h4: "Solo",
    p: "Cultural Event",
  },
  {
    date: "4:00 PM",
    h3: "Seekh Ka Baap",
    h4: "Team of 4",
    p: "Cultural Event",
  },
  {
    date: "04:30 PM",
    h3: "Electric Vehicles Seminar",
    h4: "Solo",
    p: "Technical Seminar",
  },
];

export const timeLineDataDay2 = [
  {
    date: "09:00 AM",
    h3: "Zumba",
    h4: "Solo",
    p: "Cultural Event",
  },
  {
    date: "09:00 AM",
    h3: "Financial Literacy",
    h4: "Solo",
    p: "Technical Event",
  },
  {
    date: "09:00 AM",
    h3: "Higher Studies Seminar",
    h4: "Solo",
    p: "Technical Seminar",
  },
  {
    date: "09:00 AM",
    h3: "CS-GO",
    h4: "Team of 5",
    p: "Gaming",
  },
  {
    date: "09:00 AM",
    h3: "Beast Mode",
    h4: "Solo",
    p: "Fun Event",
  },
  {
    date: "09:00 AM",
    h3: "Self Defence",
    h4: "Solo",
    p: "Cultural Event",
  },
  {
    date: "09:30 AM",
    h3: "Skribble",
    h4: "Solo",
    p: "Fun Event",
  },
  {
    date: "09:30 AM",
    h3: "Dance Workshop",
    h4: "Solo",
    p: "Cultural Event",
  },
  {
    date: "10:00 AM",
    h3: "Colour The Cover",
    h4: "Solo",
    p: "Cultural Event",
  },
  {
    date: "10:00 AM",
    h3: "QuickType",
    h4: "Solo",
    p: "Fun Event",
  },
  {
    date: "10:00 AM",
    h3: "Basic Insights-Motorsport Technicalitites",
    h4: "Solo",
    p: "Technical Seminar",
  },
  {
    date: "10:30 AM",
    h3: "CAD-Master",
    h4: "Solo",
    p: "Technical Event",
  },
  {
    date: "11:00 AM",
    h3: "Blockchain Based Security For IoT",
    h4: "Solo",
    p: "Technical Seminar",
  },
  {
    date: "11:00 AM",
    h3: "Technical Paper Presentation",
    h4: "Team of 1-2",
    p: "Technical Event",
  },
  {
    date: "11:00 AM",
    h3: "Cook off Challenge (MasterChef)",
    h4: "Solo",
    p: "Cultural Event",
  },
  {
    date: "11:00 AM",
    h3: "Emotional Intelligence",
    h4: "Solo",
    p: "Cultural Seminar",
  },
  {
    date: "12:00 PM",
    h3: "Valorant",
    h4: "Team of 5",
    p: "Gaming",
  },
  {
    date: "12:00 PM",
    h3: "AI Based Antivirus Softwares",
    h4: "Solo",
    p: "Technical Seminar",
  },
  {
    date: "12:00 PM",
    h3: "Hack It Out",
    h4: "Team of 1-5",
    p: "Technical Event",
  },
  {
    date: "12:00 PM",
    h3: "Code-O-Quick",
    h4: "Solo",
    p: "Technical Event",
  },
  {
    date: "12:30 PM",
    h3: "Ohh Reely",
    h4: "Solo",
    p: "Cultural Event",
  },
  {
    date: "03:00 PM",
    h3: "Rocket League",
    h4: "Team of 2-3",
    p: "Gaming",
  },
  {
    date: "04:00 PM",
    h3: "Technical Treasure Hunt",
    h4: "Team of 2",
    p: "Technical Event",
  },
  {
    date: "04:00 PM",
    h3: "Spill The Ink",
    h4: "Solo",
    p: "Cultural Event"
  },
  {
    date: "04:30 PM",
    h3: "Kalakriti",
    h4: "Solo",
    p: "Cultural Event",
  },
];

export const timeLineDataDay3 = [
  {
    date: "09:00 AM",
    h3: "Yoga",
    h4: "Solo",
    p: "Cultural Event",
  },
  {
    date: "09:00 AM",
    h3: "Robotics Process Automation",
    h4: "Solo",
    p: "Technical Seminar",
  },
  {
    date: "09:00 AM",
    h3: "Rocket League",
    h4: "Team of 2-3",
    p: "Gaming",
  },
  {
    date: "09:30 PM",
    h3: "Self Defence",
    h4: "Solo",
    p: "Cultural Event",
  },
  {
    date: "10:00 AM",
    h3: "Among Us",
    h4: "Solo",
    p: "Fun Event",
  },
  {
    date: "10:00 AM",
    h3: "Capture The Flag-Story Mode",
    h4: "Solo",
    p: "Technical Seminar",
  },
  {
    date: "10:00 AM",
    h3: "Isharon Isharon Mein",
    h4: "Team of 3",
    p: "Cultural Event",
  },
  {
    date: "10:00 AM",
    h3: "Dhrishya",
    h4: "Solo",
    p: "Cultural Event",
  },
  {
    date: "10:00 AM",
    h3: "Dance Workshop",
    h4: "Solo",
    p: "Cultural Event",
  },
  {
    date: "10:30 AM",
    h3: "Jingle Bells",
    h4: "Solo",
    p: "Cultural Event",
  },
  {
    date: "10:30 AM",
    h3: "Higher Studies Seminar",
    h4: "Solo",
    p: "Technical Seminar",
  },
  {
    date: "11:00 AM",
    h3: "COD Mobile",
    h4: "Team of 4",
    p: "Fun Event",
  },
  {
    date: "11:00 AM",
    h3: "Marketing And Sales",
    h4: "Team of 2",
    p: "Technical Event",
  },
  {
    date: "11:30 AM",
    h3: "Avidhrita",
    h4: "Team of 3",
    p: "Technical Event",
  },
  {
    date: "11:30 AM",
    h3: "Judge By The Cover",
    h4: "Solo",
    p: "Cultural Event",
  },
  {
    date: "11:30 PM",
    h3: "Web Technologies",
    h4: "Solo",
    p: "Technical Event",
  },
  {
    date: "12:00 PM",
    h3: "Google's Driverless Cars and Sophia",
    h4: "Solo",
    p: "Technical Seminar",
  },
  {
    date: "01:00 PM",
    h3: "CS-GO",
    h4: "Team of 5",
    p: "Gaming",
  },
  {
    date: "02:00 PM",
    h3: "You're a Quizard, Harry!",
    h4: "Team of 3",
    p: "Cultural Event",
  },
  {
    date: "02:30 PM",
    h3: "Quiz X",
    h4: "Solo",
    p: "Technical Event",
  },
  {
    date: "04:00 PM",
    h3: "Valorant",
    h4: "Team of 5",
    p: "Gaming",
  },
  {
    date: "04:30 PM",
    h3: "Poster Presentation",
    h4: "Team of 1-2",
    p: "Technical Seminar",
  },
  {
    date: "04:30 PM",
    h3: "Bug Hunter",
    h4: "Solo",
    p: "Technical Event",
  },
  {
    date: "05:00 PM",
    h3: "Mr And Ms Etamax",
    h4: "Solo",
    p: "Cultural Event",
  },
];
